# fly.toml app configuration file generated for firefinder on 2025-09-01T20:44:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firefinder'
primary_region = 'sjc'

[build]
  build_secrets = { PUBLIC_MAPBOX_TOKEN = "from_secret" }

[env]
  PUBLIC_MAPBOX_TOKEN = { from_secret = "PUBLIC_MAPBOX_TOKEN" }

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
